### ISSUE TITLE
grass tiles bug

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#10]
a bug appears  when drawing trees with the first brush (a green square inside the tiles)
![capture d ecran 2016-08-27 a 20 50 31](https://cloud.githubusercontent.com/assets/21156775/18029429/20aea6d4-6c98-11e6-805e-0faea51326b0.png)

**Comment by jeanguyomarch** [comment]
Should not happen anymore now. Toolbar will have a visual bug (will visually select something it should not select), but it is not actually selected. Might be a bug from the EFL.

**Comment by jonolemon** [comment]
Thanks !  ^-^
