### ISSUE TITLE
crash of War2 at start up

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#11]
[sauvez le mage.pud.zip](https://github.com/jeanguyomarch/war2edit/files/440800/sauvez.le.mage.pud.zip)

**Comment by jeanguyomarch** [comment]
Ok, that's the orc transport which makes everything crash...

**Comment by jeanguyomarch** [comment]
aaaaaah I get it.
alignment on water!!!!!! Same issue as in #9. Should be easy to fix.

**Comment by jonolemon** [comment]
Thanks ! It's works perfectly well !
