### ISSUE TITLE
undo breaks save

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#15]
1. do stuff
2. save: OK
3. undo: OK
4. save: doesn't work

**Comment by jeanguyomarch** [comment]
Ok, I can reproduce that. Thanks for reporting.

**Comment by jeanguyomarch** [comment]
To be a bit more specific, it's when you have to undo a unit creation/deletion. There is a counter that gets out of sync. It gets caught by safety checks and saving fails. That's actualy a good thing, we ensure we are not writing garbage into the PUD file :-)
