### ISSUE TITLE
Button "continue" is missing in the score's window

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#5]
When the game is finished, the scores were listed properly but there is no "continue" button and we had to use the escape key to return to the game.
[Issue_1_btn_continue.pdf](https://github.com/jeanguyomarch/war2edit/files/433301/Issue_1_btn_continue.pdf)

**Comment by jeanguyomarch** [comment]
It is also weird that all 8 players are listed, instead of just two...

**Comment by jeanguyomarch** [comment]
Seems like a bug in Warcraft II... I have found what triggerred it. It has been fixed in libpud (https://github.com/jeanguyomarch/war2tools/commit/3ecccc824d5276124dca34f911c96d3b68412a3b)
Thanks for the report.

**Comment by jonolemon** [comment]
it works !
