### ISSUE TITLE
Btn "continue" missing in case of defeat

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#6]
In case of defeat the button "continue" is still missing

[Issue_2_btn_defeat.pdf](https://github.com/jeanguyomarch/war2edit/files/437206/Issue_2_btn_defeat.pdf)

**Comment by jeanguyomarch** [comment]
You do not have the version that fixes the bug (I've done that yesterday).
Please reopen if the problem is still there with the new version.

**Comment by jonolemon** [comment]
Yes !
