### ISSUE TITLE
Walls issue

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#7]
The game's characters are not stopped by the walls. The walls appeared in black 
[walls issue.pdf](https://github.com/jeanguyomarch/war2edit/files/437221/walls.issue.pdf)

**Comment by jeanguyomarch** [comment]
Did you:
1. create the walls yourself or
2. were they already provided by a PUD?

Also, can you please provide your screenshots as normal jpg (or png) so it will be well displayed?
Here is a link (FR) that describes how to use Mac OS X capture tool: https://support.apple.com/fr-fr/HT201361

**Comment by jonolemon** [comment]
by myself … but,  I just saw in the TODO and BUGS that the walls are not yet available
